routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', 'HomeController@homepage');
Route::resource('admin', 'AdminsController');

app/Admin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
class Admin extends Authenticatable
{
     protected $fillable = ['email','middle_name','full_name','first_name','last_name', 'mobile_no', 'password','gender', 'is_active','is_delete'];
    //not using the default table name as per laravel convention which will be products
    protected $table = 'admin';
    //mark columns as dates - this gives us carbon instances of these dates automatically
    protected $dates = ['created_at', 'updated_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Admin;
use DB;
use Config;
use Session;
use Auth;
use Storage;
use Hash;
class AdminsController extends Controller
{
   /* public function __construct() {
        $this->middleware('auth:admin', ['except' => array('login')]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       /* $data = array();
        $session_data = session()->get('filterSession');
        if (!empty($session_data['search_text'])) {
            $data[] = ['admin.full_name', 'LIKE', '%' . $session_data['search_text'] . '%'];
            // dd($data);
        }*/
        $admins = DB::table('admin')
        //->where($data)
        ->select('admin.*')
        ->paginate(25);
        
      //  flash()->success('Admin Created Successfully');
        return view('admin.index',compact('admins'));
    }

    
    public function create()
    {
        return view('admin.create', compact(''));
    }

    public function store(Request $request)
    {
        $exist = Admin::where('email', '=', $request->email)->first();
        if (empty($exist)) {
            $request->request->add(['created_by' => 1, 'updated_by' => 1, 'password' => bcrypt($request->password), 'first_name' => ucwords($request->first_name), 'last_name' => ucwords($request->last_name),'is_active' => '1', 'role' => 1]);
            $admin = new Admin();
            $admin->full_name = ucwords($request->first_name) . ' ' . ucwords($request->last_name);
            $admin->is_delete = 1;
           /* $user = Auth::guard('admin')->user();
            if (!empty($user)) {
                $admin->created_by = $user->id;
                $admin->modified_by = $user->id;
            } else {
                $admin->created_by = 1;
                $admin->modified_by = 1;
            }*/
            $admin->fill($request->all()); //sets the right values
            $admin->save();
            $request->session()->flash('success', 'Admin Created Successfully');
            return redirect()->route('admin.index');
        } else {
            $request->session()->flash('errors', 'This Email Already Exists');
            return redirect()->route('admin.create');
        }
        return redirect()->route('admin.create');
    }

        public function edit($id)
    {
        $data = Admin::find($id);
        $status = Config::get('aarogyam.status');
        return view('admin.edit', compact('data','status'));
    }

    
    public function update(Request $request, $id)
    {
        $admin = Admin::find($id);
        $admin->fill($request->all());
        $admin->first_name = ucwords($request->first_name);
        $admin->last_name = ucwords($request->last_name);
        $admin->full_name = ucwords($request->first_name) . ' ' . ucwords($request->last_name);
        $admin->updated_at = date('Y-m-d H:i:s');
        if ($admin->save()) {
            $request->session()->flash('success', 'Admin Has Been Updated!');
        } else {
            $request->session()->flash('errors', 'Unable To Update Admin!');
        }
        return redirect()->route('admin.index');
    }
    /*
    public function activate($id, $status) {
        $admin = Admin::find($id);
        $admin->is_active = $status;
        if($status==0){
            \Session::flash('flash_message', 'Admin Deactivated Successfully!');
        }
        else{
            \Session::flash('flash_message', 'Admin Activated Successfully!');
        }
        
        $admin->save();
        return redirect()->route('admin.index');
    }
    public function login() {
        return view('admin_login');
    }

    
    
    public function ChangePassword(Request $request)
    {
        return view('admin.admin.changePassword');
    }
    public function updatePassword(Request $request)
    {
        // dd($request);
        $user = Auth::guard('admin')->user();
        $check=Hash::check($request->oldPassword, $user->password, []);
        if($check == 'true'){
         $change = Admin::find($user->id);
         $change->password = bcrypt($request->newPassword);
          if($change->save()){
            Session()->flash('success', 'Admin Has Been Updated!');
          }
          else{
            Session()->flash('errors', 'Unable To Update Admin!');
          }
        } else{
        Session()->flash('errors', 'Password do not match');
        }
    
    return redirect()->route('admin.index');
    }
    */
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Config;
use Session;
use Auth;
use Storage;
use Hash;
class HomeController extends Controller
{
    public function homepage()
    {
        return view('layout.app');
        return redirect()->route('layout.app');
    }

}

?>

resources/views/admin/create.blade.php
@extends('layout.app')
@section('content')
<div class="content-wrapper">
   
    <!-- Main content -->
    <section class="content">

        <!-- COLOR PALETTE -->
        <div class="box box-default color-palette-box">
            <div class="box-header with-border">
                <h3 class="box-title">Admin Details</h3>
            </div>

            <form action="{{route('admin.store')}}" method="post" id="add_form"  class="center-block">
            {{csrf_field()}}
                <div class="box-body">
                    <div class="col-md-12">

                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>First Name <span class="error">*</span></label>
                                    <input type="text" class="form-control allCaps" name="first_name" data-bvalidator="required,alpha" placeholder="First Name">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Last Name <span class="error">*</span></label>
                                    <input type="text" class="form-control allCaps" name="last_name" data-bvalidator="required,alpha" placeholder="Last Name">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Email Address <span class="error">*</span></label>
                                    <input type="email" class="form-control" autocomplete="off" name="email" data-bvalidator="required" placeholder="Email Address">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Password <span class="error">*</span></label>
                                    <input type="password" class="form-control" autocomplete="off" id="pass" name="password" data-bvalidator="required" placeholder="Password">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Confirm Password <span class="error">*</span></label>
                                    <input type="password" class="form-control" name="c_password" autocomplete="off" data-bvalidator="required,equal[pass]" placeholder="Confirm Password">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                           <div class="col-sm-6">                                   
                                <div class="form-group">
                                    <label  class="form-group">Mobile No<span class="requird">*</span></label>   
                                    <input type="mobile" class="form-control onlyNumbers" maxlength="10" minlength="10" name="mobile_no" data-bvalidator="required" placeholder="Mobile">
                                </div>                              
                            </div> 
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->

                <div class="tab-content">
                    <div class="tab-pane active" role="tabpanel" id="step1">
                        <div class="box-footer">    
                            <div class="col-md-6"> 

                                <button type="submit" class="btn btn-primary">Save</button>
                                <a class="btn btn-primary prev-step" href="{{route('admin.index')}}" type="submit">Cancel</a>
                            </div> 
                        </div>
                    </div>
                </div>   
            </form>
        </div>
        <!-- /.box -->

        <!-- /.box-body -->


    </section>
    <!-- /.content -->

</div>
<!--<script type="text/javascript">
    $(document).ready(function () {
        $('#add_form').bValidator();
    });
</script>-->
@endsection

resources/views/admin/edit.blade.php
@extends('layout.app')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
          @include('element.flash')
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- COLOR PALETTE -->
        <div class="box box-default color-palette-box">
            <div class="box-header with-border">
                <h3 class="box-title">Admin Edit</h3>
            </div>

            <form action="{{route('admin.update',$data)}}" method="post" id="edit_admin"  class="center-block">
                {{csrf_field()}}
                {{ method_field('PATCH')}}
                <div class="box-body">
                    <div class="col-md-12">

                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>First Name <span class="error">*</span></label>
                                    <input type="text" value="{{ old('first_name',$data->first_name) }}" class="form-control allCaps" name="first_name" data-bvalidator="required,alpha" placeholder="First Name">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Last Name <span class="error">*</span></label>
                                    <input type="text" value="{{ old('last_name',$data->last_name) }}" class="form-control allCaps" name="last_name" data-bvalidator="required,alpha" placeholder="Last Name">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Email<span class="error">*</span></label>
                                    <input type="email" value="{{ old('email',$data->email) }}" class="form-control" name="email" data-bvalidator="required" placeholder="Email">
                                </div>
                            </div>
                        </div>
                        <div class="row"> 
                           <div class="col-sm-6">                                   
                                <div class="form-group">
                                    <label  class="form-group">Mobile No<span class="requird">*</span></label>   
                                    <input type="mobile" class="form-control onlyNumbers" value="{{ old('mobile_no',$data->mobile_no) }}" maxlength="10" minlength="10" name="mobile_no" data-bvalidator="required,digit" placeholder="Mobile">
                                </div>                              
                            </div> 
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->

                <div class="tab-content">
                    <div class="tab-pane active" role="tabpanel" id="step1">
                        <div class="box-footer">    
                            <div class="col-md-6"> 

                                <button type="submit" class="btn btn-primary">Save</button>
                                <a class="btn btn-primary prev-step" href="{{route('admin.index')}}" type="submit">Cancel</a>
                            </div> 
                        </div>
                    </div>
                </div>   
            </form>
        </div>
        <!-- /.box -->

        <!-- /.box-body -->


    </section>
    <!-- /.content -->



</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#edit_admin').bValidator();

    });
</script>
@endsection

resources/views/admin/index.blade.php
@extends('layout.app')
@section('content')
<div class="content-wrapper">
    
    <section class="content">
        <div class="box box-default ">
            <div class="box-header with-border">
                <h3 class="box-title">Admin Users</h3>
                <div class="pull-right">
                        <a href="{{route('admin.create')}}" class="btn btn-info float-right">
                            <i class="fa fa-plus"></i> Admin
                        </a>
                </div><br><br>
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-12">
                    <table  id="table1" class="display table table-bordered table-striped table-hover" border="1">
                        <thead> 
                            <tr>
                                <th>Sr.No</th>
                                <th>Full Name</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="myTable">
                            @if(count($admins) == 0)
                            <tr class="odd">
                                <td colspan='8'>No search results found<td>
                            </tr>
                            @else
                            
                           <?php $i = ($admins->currentPage() == 1) ? 1 : $admins->currentPage() + 24; ?>
                            @foreach($admins as $key => $value)
                            <tr>
                                <td>{{ $i++}}</td>
                                <td>{{ $value->full_name}}</td>
                                <td>{{ $value->email}}</td>
                                <td>{{ $value->mobile_no}}</td>
                                <td>{{ ($value->is_active==1)?'Active':'Deactive'}}</td>
                                <td>{{ $value->created_at}}</td>
                                <td>
                                        <a href="{{ route('admin.edit',$value->id) }}" title="Edit" type="button" data-toggle="tooltip" ><i class="fa fa-edit"  style="font-size:16px"></i></a>                     
                                        @if($value->is_active == '1')
                                        <a href="{{ url('admin/activate/'.$value->id,0) }}" title="Deactivate" data-toggle="tooltip"  onclick="return confirm('Are you sure you want to deactivate this?');" type="button"><i class="fa fa-times" style="font-size:16px" ></i></a>
                                        @else 
                                        <a href="{{ url('admin/activate/'.$value->id,1) }}" title="Activate" data-toggle="tooltip"  onclick="return confirm('Are you sure you want to Activate this?');" type="button"><i class="fa fa-check" style="font-size:16px"></i></a>
                                        @endif
                                </td> 
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>    
                </div>
                <nav class="text-right">
                    @if ($admins->lastPage() > 1)
                    <ul class="pagination">
                        <li class="page-item {{ ($admins->currentPage() == 1) ? ' disabled' : '' }}">
                            <a class="page-link" href="{{ $admins->url($admins->currentPage() - 1) }}">Prev</a>
                        </li>
                        @for ($i = 1; $i <= $admins->lastPage(); $i++)
                        <li class="page-item {{ ($admins->currentPage() == $i) ? ' active' : '' }}">
                            <a class="page-link" href="{{ $admins->url($i) }}">{{ $i }}</a>
                        </li>
                        @endfor
                        <li class="page-item {{ ($admins->currentPage() == $admins->lastPage()) ? ' disabled' : '' }}">
                            <a class="page-link" href="{{ $admins->url($admins->currentPage()+1) }}" >Next</a>
                        </li>
                    </ul>
                    @endif
                </nav>

            </div>

        </div>
    </section>
</div>

@endsection

resources/views/element/flash.blade.php
@if (session()->has('errors'))
    <div class="alert alert-danger animated fadeIn">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {!! session()->get('errors') !!}
        </strong>
    </div>
@endif
@if (session()->has('success'))
    <div class="alert alert-success animated fadeIn">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {!! session()->get('success') !!}
        </strong>
    </div>
@endif

resources/views/element/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.5
    </div>
  </footer>

resources/views/element/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>
    <!-- SEARCH FORM -->
    
  </nav>

resources/views/element/slider.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ url('/') }}/public/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="./index.html" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v1</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="./index2.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v2</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="./index3.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v3</p>
                </a>
              </li>
            </ul>
          </li>
        
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <!-- Font Awesome -->
  <!-- <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css"> -->
  {!! Html::style('public/css/all.min.css') !!}
  {!! Html::style('public/css/tempusdominus-bootstrap-4.min.css') !!}
  {!! Html::style('public/css/icheck-bootstrap.min.css') !!}
 
  {!! Html::style('public/css/adminlte.min.css') !!}
  {!! Html::style('public/css/OverlayScrollbars.min.css') !!}
  {!! Html::style('public/css/daterangepicker.css') !!}
  {!! Html::style('public/css/summernote-bs4.css') !!}
  
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition skin-blue sidebar-mini"style="padding: 0px">
<div class="wrapper">

            @include('element.header')
            @include('element.slider')
            @yield('content')
            @include('element.footer')
 
</div>
<!-- ./wrapper -->

<!-- jQuery -->

{!! Html::script('public/js/jquery.min.js')!!}
{!! Html::script('public/js/jquery-ui.min.js')!!}
{!! Html::script('public/js/bootstrap.bundle.min.js')!!}
{!! Html::script('public/js/Chart.min.js')!!}
{!! Html::script('public/js/sparkline.js')!!}
{!! Html::script('public/js/jquery.knob.min.js')!!}
{!! Html::script('public/js/moment.min.js')!!}
{!! Html::script('public/js/daterangepicker.js')!!}
{!! Html::script('public/js/tempusdominus-bootstrap-4.min.js')!!}
{!! Html::script('public/js/summernote-bs4.min.js')!!}
{!! Html::script('public/js/jquery.overlayScrollbars.min.js')!!}
{!! Html::script('public/js/adminlte.js')!!}
{!! Html::script('public/js/dashboard.js')!!}
{!! Html::script('public/js/demo.js')!!}

<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
</body>
</html>